/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase_25082025;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author claudiacortes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        // Limpieza del combobox 

        DefaultComboBoxModel modeloComboBox = new DefaultComboBoxModel();
        jcb_usuarios.setModel(modeloComboBox);
        jcb_listar.setModel(modeloComboBox);
        jcb_modificar.setModel(modeloComboBox);
        jcb_eliminar.setModel(modeloComboBox);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtb_opciones = new javax.swing.JTabbedPane();
        jp_modificar = new javax.swing.JPanel();
        lbl_modificar_label = new javax.swing.JLabel();
        txt_nombreModificar = new javax.swing.JTextField();
        btn_modificar = new javax.swing.JButton();
        jcb_modificar = new javax.swing.JComboBox<>();
        jp_eliminar = new javax.swing.JPanel();
        jcb_eliminar = new javax.swing.JComboBox<>();
        btn_eliminar = new javax.swing.JButton();
        jp_listar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_listar_nombre = new javax.swing.JLabel();
        lbl_listar_pos = new javax.swing.JLabel();
        lbl_nombreDisplay = new javax.swing.JLabel();
        lbl_posDisplay = new javax.swing.JLabel();
        jcb_listar = new javax.swing.JComboBox<>();
        jp_agregar = new javax.swing.JPanel();
        btn_agregar = new javax.swing.JButton();
        jcb_usuarios = new javax.swing.JComboBox<>();
        lbl_nombre = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_modificar_label.setText("nombre");

        btn_modificar.setText("modificar");
        btn_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificarMouseClicked(evt);
            }
        });

        jcb_modificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_modificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_modificarLayout = new javax.swing.GroupLayout(jp_modificar);
        jp_modificar.setLayout(jp_modificarLayout);
        jp_modificarLayout.setHorizontalGroup(
            jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_modificarLayout.createSequentialGroup()
                .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jp_modificarLayout.createSequentialGroup()
                            .addGap(265, 265, 265)
                            .addComponent(jcb_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_modificarLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_modificar)))
                    .addGroup(jp_modificarLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lbl_modificar_label)
                        .addGap(46, 46, 46)
                        .addComponent(txt_nombreModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(349, Short.MAX_VALUE))
        );
        jp_modificarLayout.setVerticalGroup(
            jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_modificarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jcb_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jp_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_modificar_label)
                    .addComponent(txt_nombreModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addComponent(btn_modificar)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        jtb_opciones.addTab("Modificar", jp_modificar);

        jcb_eliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_eliminar.setText("elminar");
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_eliminarLayout = new javax.swing.GroupLayout(jp_eliminar);
        jp_eliminar.setLayout(jp_eliminarLayout);
        jp_eliminarLayout.setHorizontalGroup(
            jp_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_eliminarLayout.createSequentialGroup()
                .addGroup(jp_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_eliminarLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jcb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_eliminarLayout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(btn_eliminar)))
                .addContainerGap(450, Short.MAX_VALUE))
        );
        jp_eliminarLayout.setVerticalGroup(
            jp_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_eliminarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jcb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(btn_eliminar)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        jtb_opciones.addTab("Eliminar", jp_eliminar);

        jLabel1.setText("Datos");

        lbl_listar_nombre.setText("Nombre");

        lbl_listar_pos.setText("Pos");

        jcb_listar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_listarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_listarLayout = new javax.swing.GroupLayout(jp_listar);
        jp_listar.setLayout(jp_listarLayout);
        jp_listarLayout.setHorizontalGroup(
            jp_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_listarLayout.createSequentialGroup()
                .addGroup(jp_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_listarLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jp_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_listar_nombre)
                            .addComponent(lbl_nombreDisplay))
                        .addGap(190, 190, 190)
                        .addGroup(jp_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jp_listarLayout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addGroup(jp_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_posDisplay)
                                    .addComponent(lbl_listar_pos)))))
                    .addGroup(jp_listarLayout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jcb_listar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(365, Short.MAX_VALUE))
        );
        jp_listarLayout.setVerticalGroup(
            jp_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_listarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcb_listar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addGroup(jp_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_listar_nombre)
                    .addComponent(lbl_listar_pos))
                .addGap(33, 33, 33)
                .addGroup(jp_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombreDisplay)
                    .addComponent(lbl_posDisplay))
                .addContainerGap(224, Short.MAX_VALUE))
        );

        jtb_opciones.addTab("Listar", jp_listar);

        btn_agregar.setText("Agregar");
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarMouseClicked(evt);
            }
        });

        jcb_usuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hola Mundo" }));

        lbl_nombre.setText("Nombre");

        javax.swing.GroupLayout jp_agregarLayout = new javax.swing.GroupLayout(jp_agregar);
        jp_agregar.setLayout(jp_agregarLayout);
        jp_agregarLayout.setHorizontalGroup(
            jp_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_agregarLayout.createSequentialGroup()
                .addGroup(jp_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_agregarLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lbl_nombre)
                        .addGap(166, 166, 166)
                        .addGroup(jp_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcb_usuarios, 0, 333, Short.MAX_VALUE)
                            .addComponent(txt_nombre)))
                    .addGroup(jp_agregarLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(btn_agregar)))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        jp_agregarLayout.setVerticalGroup(
            jp_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_agregarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jcb_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jp_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nombre)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(btn_agregar)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        jtb_opciones.addTab("Agregar", jp_agregar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtb_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtb_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseClicked
        String nombreUsuario = txt_nombre.getText();
        Usuario nuevoUser = new Usuario(nombreUsuario);
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) jcb_usuarios.getModel();
        modelo.addElement(nuevoUser);

        JOptionPane.showMessageDialog(this, "Usuario creado " + nuevoUser);

    }//GEN-LAST:event_btn_agregarMouseClicked

    private void jcb_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_listarActionPerformed
        int pos = jcb_listar.getSelectedIndex();
        lbl_posDisplay.setText("" + pos);

        Object seleccionado = jcb_listar.getSelectedItem();
        if (seleccionado instanceof Usuario) {
            Usuario u = (Usuario) seleccionado;
            lbl_nombreDisplay.setText(u.getNombre());
        }

    }//GEN-LAST:event_jcb_listarActionPerformed

    private void jcb_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_modificarActionPerformed
        Object selecicoando = jcb_modificar.getSelectedItem();
        if (selecicoando instanceof Usuario) {
            Usuario u = (Usuario) selecicoando;
            txt_nombreModificar.setText(u.getNombre());
//                    txt_nombreModificar.setText(((Usuario)selecicoando).getNombre());
        }
    }//GEN-LAST:event_jcb_modificarActionPerformed

    private void btn_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarMouseClicked
        Object selecicoando = jcb_modificar.getSelectedItem();
        if (selecicoando instanceof Usuario) {
            Usuario u = (Usuario) selecicoando;
            String nombre = txt_nombreModificar.getText();
            u.setNombre(nombre);
             JOptionPane.showMessageDialog(this, "Usuario Modificado " );
        }
    }//GEN-LAST:event_btn_modificarMouseClicked

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
        int pos = jcb_eliminar.getSelectedIndex();
          DefaultComboBoxModel modelo = (DefaultComboBoxModel) jcb_eliminar.getModel();
          modelo.removeElementAt(pos);
          JOptionPane.showMessageDialog(this, "Usuario eliminado " );
    }//GEN-LAST:event_btn_eliminarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> jcb_eliminar;
    private javax.swing.JComboBox<String> jcb_listar;
    private javax.swing.JComboBox<String> jcb_modificar;
    private javax.swing.JComboBox<String> jcb_usuarios;
    private javax.swing.JPanel jp_agregar;
    private javax.swing.JPanel jp_eliminar;
    private javax.swing.JPanel jp_listar;
    private javax.swing.JPanel jp_modificar;
    private javax.swing.JTabbedPane jtb_opciones;
    private javax.swing.JLabel lbl_listar_nombre;
    private javax.swing.JLabel lbl_listar_pos;
    private javax.swing.JLabel lbl_modificar_label;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_nombreDisplay;
    private javax.swing.JLabel lbl_posDisplay;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombreModificar;
    // End of variables declaration//GEN-END:variables
}
