/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase_01092025;

import java.awt.Color;
import java.awt.Font;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;

/**
 *
 * @author claudiacortes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        DefaultListModel model = new DefaultListModel();
        jl_usuarios.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_abrir = new javax.swing.JDialog();
        lbl_edicion = new javax.swing.JLabel();
        txt_texto = new javax.swing.JTextField();
        btn_actualizar = new javax.swing.JButton();
        txt_size = new javax.swing.JTextField();
        btn_actualizarSize = new javax.swing.JButton();
        txt_font = new javax.swing.JTextField();
        btn_actualizarFont = new javax.swing.JButton();
        jcb_styles = new javax.swing.JComboBox<>();
        btn_changeBgColor = new javax.swing.JButton();
        btn_changeForeGroundColor = new javax.swing.JButton();
        jpm_opciones = new javax.swing.JPopupMenu();
        jmi_elemento1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        popupMenu1 = new java.awt.PopupMenu();
        menuItem1 = new java.awt.MenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_usuarios = new javax.swing.JList<>();
        txt_nombre = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        lbl_selecionado = new javax.swing.JLabel();
        btn_editar = new javax.swing.JButton();
        jmb_menu = new javax.swing.JMenuBar();
        jm_file = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jmi_click = new javax.swing.JMenuItem();
        jm_edit = new javax.swing.JMenu();

        btn_actualizar.setText("cambiar");
        btn_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarMouseClicked(evt);
            }
        });

        btn_actualizarSize.setText("Actualizar");
        btn_actualizarSize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarSizeMouseClicked(evt);
            }
        });

        btn_actualizarFont.setText("Actualizar");
        btn_actualizarFont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarFontMouseClicked(evt);
            }
        });

        jcb_styles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negrita", "Italica", "Normal" }));
        jcb_styles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_stylesActionPerformed(evt);
            }
        });

        btn_changeBgColor.setText("Cambiar BG");
        btn_changeBgColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_changeBgColorMouseClicked(evt);
            }
        });

        btn_changeForeGroundColor.setText("Cambiar Font");
        btn_changeForeGroundColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_changeForeGroundColorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_abrirLayout = new javax.swing.GroupLayout(jd_abrir.getContentPane());
        jd_abrir.getContentPane().setLayout(jd_abrirLayout);
        jd_abrirLayout.setHorizontalGroup(
            jd_abrirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_abrirLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(lbl_edicion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_abrirLayout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(jd_abrirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jd_abrirLayout.createSequentialGroup()
                        .addGroup(jd_abrirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_abrirLayout.createSequentialGroup()
                                .addGroup(jd_abrirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_texto)
                                    .addComponent(txt_size)
                                    .addComponent(txt_font, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jd_abrirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_actualizarSize)
                                    .addComponent(btn_actualizar)
                                    .addComponent(btn_actualizarFont, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jcb_styles, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46))
                    .addGroup(jd_abrirLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btn_changeForeGroundColor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                        .addComponent(btn_changeBgColor)
                        .addGap(137, 137, 137))))
        );
        jd_abrirLayout.setVerticalGroup(
            jd_abrirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_abrirLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lbl_edicion)
                .addGap(18, 18, 18)
                .addGroup(jd_abrirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_actualizar))
                .addGap(43, 43, 43)
                .addGroup(jd_abrirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_actualizarSize))
                .addGap(18, 18, 18)
                .addGroup(jd_abrirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_font, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_actualizarFont))
                .addGap(35, 35, 35)
                .addComponent(jcb_styles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jd_abrirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_changeBgColor)
                    .addComponent(btn_changeForeGroundColor))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jmi_elemento1.setText("Mostrar");
        jpm_opciones.add(jmi_elemento1);

        jMenuItem3.setText("jMenuItem3");
        jpm_opciones.add(jMenuItem3);

        jMenuItem4.setText("jMenuItem4");
        jpm_opciones.add(jMenuItem4);

        popupMenu1.setLabel("popupMenu1");

        menuItem1.setLabel("menuItem1");
        popupMenu1.add(menuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jl_usuarios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jl_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_usuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_usuarios);

        btn_agregar.setText("Agregar");
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarMouseClicked(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
        });

        btn_editar.setText("Editar");
        btn_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editarMouseClicked(evt);
            }
        });

        jm_file.setText("File");

        jMenu1.setText("Imprimir");

        jMenu2.setText("jMenu2");
        jMenu1.add(jMenu2);

        jMenuItem2.setText("jMenuItem2");
        jMenu1.add(jMenuItem2);

        jm_file.add(jMenu1);

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jm_file.add(jMenuItem1);
        jm_file.add(jSeparator1);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");
        jm_file.add(jCheckBoxMenuItem1);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");
        jm_file.add(jRadioButtonMenuItem1);

        jmi_click.setText("click");
        jmi_click.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmi_clickMouseClicked(evt);
            }
        });
        jm_file.add(jmi_click);

        jmb_menu.add(jm_file);

        jm_edit.setText("edit");
        jmb_menu.add(jm_edit);

        setJMenuBar(jmb_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nombre)
                            .addComponent(btn_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(btn_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(lbl_selecionado)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(lbl_selecionado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_agregar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_editar)))
                .addContainerGap(245, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jd_abrir.setVisible(true);
        jd_abrir.pack();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmi_clickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmi_clickMouseClicked
        jd_abrir.setVisible(true);
        jd_abrir.pack();
    }//GEN-LAST:event_jmi_clickMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

        switch (evt.getButton()) {
            case 1:
                System.out.println("Click izq");
                break;
            case 3:
                jpm_opciones.show(this, evt.getX(), evt.getY());
            default:
                System.out.println("Otro tipo de click");
        }

    }//GEN-LAST:event_formMouseClicked

    private void btn_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseClicked
        DefaultListModel model = (DefaultListModel) jl_usuarios.getModel();
        Usuario u = new Usuario(txt_nombre.getText());
        model.addElement(u);
    }//GEN-LAST:event_btn_agregarMouseClicked

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
        int pos = jl_usuarios.getSelectedIndex();
        DefaultListModel model = (DefaultListModel) jl_usuarios.getModel();
        model.remove(pos);

    }//GEN-LAST:event_btn_eliminarMouseClicked

    private void jl_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_usuariosMouseClicked
        switch (evt.getButton()) {
            case 1:
                int pos = jl_usuarios.getSelectedIndex();
                DefaultListModel model = (DefaultListModel) jl_usuarios.getModel();
                Object objetoSeleccionado = model.getElementAt(pos);
                if (objetoSeleccionado instanceof Usuario) {
                    Usuario seleccionado = (Usuario) objetoSeleccionado;
                    lbl_selecionado.setText(seleccionado.getNombre());
                }
                break;
            case 3:
                jpm_opciones.show(this.jl_usuarios, evt.getX(), evt.getY());
                break;
            default:
                throw new AssertionError();
        }

    }//GEN-LAST:event_jl_usuariosMouseClicked

    private void btn_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editarMouseClicked
        int pos = jl_usuarios.getSelectedIndex();
        DefaultListModel model = (DefaultListModel) jl_usuarios.getModel();
        Object objetoSeleccionado = model.getElementAt(pos);
        if (objetoSeleccionado instanceof Usuario) {
            Usuario seleccionado = (Usuario) objetoSeleccionado;
            String nuevoNombre = txt_nombre.getText();
            seleccionado.setNombre(nuevoNombre);
        }
        txt_nombre.setText("");

    }//GEN-LAST:event_btn_editarMouseClicked

    private void btn_actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarMouseClicked
        lbl_edicion.setText(txt_texto.getText());
        txt_texto.setText("");

    }//GEN-LAST:event_btn_actualizarMouseClicked

    private void btn_changeBgColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_changeBgColorMouseClicked
        Color colorSeleccionado = JColorChooser.showDialog(this, "Sleccione un color", Color.cyan);
        lbl_edicion.setOpaque(true);
        lbl_edicion.setBackground(colorSeleccionado);

    }//GEN-LAST:event_btn_changeBgColorMouseClicked

    private void btn_changeForeGroundColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_changeForeGroundColorMouseClicked
        Color colorSeleccionado = JColorChooser.showDialog(this, "Sleccione un color", Color.cyan);
        lbl_edicion.setForeground(colorSeleccionado);

    }//GEN-LAST:event_btn_changeForeGroundColorMouseClicked

    private void btn_actualizarSizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarSizeMouseClicked
        int size = Integer.parseInt(txt_size.getText());
        Font fuente = lbl_edicion.getFont();
        Font nuevafont = new Font(fuente.getFontName(), fuente.getStyle(), size);
        lbl_edicion.setFont(nuevafont);
    }//GEN-LAST:event_btn_actualizarSizeMouseClicked

    private void btn_actualizarFontMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarFontMouseClicked
        String tipo = txt_font.getText();
        Font fuente = lbl_edicion.getFont();
        Font nuevafont = new Font(tipo, fuente.getStyle(), fuente.getSize());
        lbl_edicion.setFont(nuevafont);
    }//GEN-LAST:event_btn_actualizarFontMouseClicked

    private void jcb_stylesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_stylesActionPerformed
        int style = jcb_styles.getSelectedIndex();
        int estilo ;
        switch (style) {
            case 0:
                estilo = Font.BOLD;
                break;
            case 1:
                estilo = Font.ITALIC;
                break;
            default:
                estilo = Font.PLAIN;
        }
        
        Font fuente = lbl_edicion.getFont();
        Font nuevafont = new Font(fuente.getFontName(), estilo, fuente.getSize());
        lbl_edicion.setFont(nuevafont);
    }//GEN-LAST:event_jcb_stylesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_actualizarFont;
    private javax.swing.JButton btn_actualizarSize;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_changeBgColor;
    private javax.swing.JButton btn_changeForeGroundColor;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JComboBox<String> jcb_styles;
    private javax.swing.JDialog jd_abrir;
    private javax.swing.JList<String> jl_usuarios;
    private javax.swing.JMenu jm_edit;
    private javax.swing.JMenu jm_file;
    private javax.swing.JMenuBar jmb_menu;
    private javax.swing.JMenuItem jmi_click;
    private javax.swing.JMenuItem jmi_elemento1;
    private javax.swing.JPopupMenu jpm_opciones;
    private javax.swing.JLabel lbl_edicion;
    private javax.swing.JLabel lbl_selecionado;
    private java.awt.MenuItem menuItem1;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTextField txt_font;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_size;
    private javax.swing.JTextField txt_texto;
    // End of variables declaration//GEN-END:variables
}
