/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase_19082025;

import java.util.ArrayList;

/**
 *
 * @author claudiacortes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        // Todavia no se han creado ni renderizado NINGUN elemento en la pantalla 
        initComponents();
        // Aqui si ya hay elementos mostrandose en la pantalla
        lblUsuarios.setVisible(false);
        txtListarUusarios.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblEdad = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        btnListar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtListarUusarios = new javax.swing.JTextArea();
        lblUsuarios = new javax.swing.JLabel();
        jcbOpciones = new javax.swing.JComboBox<>();
        lblOpciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombre.setBackground(new java.awt.Color(204, 255, 255));
        lblNombre.setFont(new java.awt.Font("ITF Devanagari Marathi", 3, 12)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 0, 0));
        lblNombre.setText("Nombre");
        lblNombre.setOpaque(true);

        btnCrear.setText("Crear");
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearMouseClicked(evt);
            }
        });

        btnEliminar.setText("Eliminar");

        lblEdad.setText("Edad");

        btnListar.setText("Listar");

        btnActualizar.setText("Actualizar");

        txtListarUusarios.setColumns(20);
        txtListarUusarios.setRows(5);
        jScrollPane1.setViewportView(txtListarUusarios);

        lblUsuarios.setText("Usuarios");

        jcbOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crear", "Eliminar", "Listar", "Actualizar" }));
        jcbOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbOpcionesActionPerformed(evt);
            }
        });

        lblOpciones.setText("opciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOpciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcbOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEdad)
                            .addComponent(btnCrear)
                            .addComponent(lblUsuarios))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEliminar)
                                .addGap(53, 53, 53)
                                .addComponent(btnListar)
                                .addGap(46, 46, 46)
                                .addComponent(btnActualizar))
                            .addComponent(txtNombre)
                            .addComponent(txtEdad)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOpciones))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEdad))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(lblUsuarios)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnEliminar)
                    .addComponent(btnListar)
                    .addComponent(btnActualizar))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseClicked
    String nombre = txtNombre.getText();
    
    int edad = Integer.parseInt(txtEdad.getText());
    
    // Persona p = new Persona(nombre,edad);
    // personas.add(p);
    }//GEN-LAST:event_btnCrearMouseClicked

    private void jcbOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbOpcionesActionPerformed
       int pos = jcbOpciones.getSelectedIndex();
        switch (pos) {
            case 0:
                lblNombre.setVisible(true);
                txtNombre.setVisible(true);
                lblEdad.setVisible(true);
                txtEdad.setVisible(true);
                txtListarUusarios.setVisible(false);
                lblUsuarios.setVisible(false);
                btnEliminar.setVisible(false);
                btnActualizar.setVisible(false);
                btnListar.setVisible(false);
                btnCrear.setVisible(true);
                break;
            case 1: 
                 lblNombre.setVisible(true);
                txtNombre.setVisible(true);
                lblEdad.setVisible(false);
                txtEdad.setVisible(false);
                txtListarUusarios.setVisible(false);
                lblUsuarios.setVisible(false);
                btnEliminar.setVisible(true);
                btnActualizar.setVisible(false);
                btnListar.setVisible(false);
                btnCrear.setVisible(false);
                    break;
            case  2: 
                   lblNombre.setVisible(false);
                txtNombre.setVisible(false);
                lblEdad.setVisible(false);
                txtEdad.setVisible(false);
                txtListarUusarios.setVisible(true);
                lblUsuarios.setVisible(true);
                btnEliminar.setVisible(false);
                btnActualizar.setVisible(false);
                btnListar.setVisible(true);
                btnCrear.setVisible(false);
        
                    break;
            case 3:
                   lblNombre.setVisible(true);
                txtNombre.setVisible(true);
                lblEdad.setVisible(true);
                txtEdad.setVisible(true);
                txtListarUusarios.setVisible(false);
                lblUsuarios.setVisible(false);
                btnEliminar.setVisible(false);
                btnActualizar.setVisible(false);
                btnListar.setVisible(true);
                btnCrear.setVisible(false);
                    break;
        }
    }//GEN-LAST:event_jcbOpcionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
//    ArrayList <Persona> personas = new ArrayList();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnListar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbOpciones;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblOpciones;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextArea txtListarUusarios;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
