/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase_08092025;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author claudiacortes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        // Modelo tabla 
        DefaultTableModel modeloTabla = new DefaultTableModel();
        jt_tablaUsuarios.setModel(modeloTabla);
        
        // agregar columnas 
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Cuenta");
        
        //Limpiar arbol 

    //       
//  DefaultMutableTreeNode raiz  = new DefaultMutableTreeNode("Raiz");
//  DefaultTreeModel modeloArbol = new DefaultTreeModel(raiz);
//  jt_arbolito.setModel(modeloArbol);
  
  
  
     DefaultTreeModel modeloArbol = (DefaultTreeModel) jt_arbolito.getModel();
     DefaultMutableTreeNode raiz  = (DefaultMutableTreeNode)modeloArbol.getRoot();
     raiz.setUserObject("Usuarios");
     raiz.removeAllChildren();
     

     //Agregar elementos al arbol
     
     DefaultMutableTreeNode nodoAdministrador = new DefaultMutableTreeNode("Usuarios Admin");
     DefaultMutableTreeNode nodoNormal = new DefaultMutableTreeNode("Usuarios normales");
     
     
     raiz.add(nodoAdministrador);
     raiz.add(nodoNormal);
     
      modeloArbol.reload();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jt_tablaUsuarios = new javax.swing.JTable();
        txt_nombre = new javax.swing.JTextField();
        txt_cuenta = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_fila = new javax.swing.JLabel();
        lbl_columna = new javax.swing.JLabel();
        lbl_valor = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_arbolito = new javax.swing.JTree();
        jc_tipoUusario = new javax.swing.JComboBox<>();
        btn_eliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lbl_tipoNodo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_elementoArbol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jt_tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ));
        jt_tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_tablaUsuarios);

        btn_agregar.setText("agregar");
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarMouseClicked(evt);
            }
        });

        jLabel1.setText("Fila");

        jLabel2.setText("Columna");

        jLabel3.setText("Valor");

        lbl_fila.setText("jLabel4");

        lbl_columna.setText("jLabel5");

        lbl_valor.setText("jLabel6");

        jt_arbolito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_arbolitoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jt_arbolito);

        jc_tipoUusario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Normal" }));

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
        });

        jLabel4.setText("Tipo");

        lbl_tipoNodo.setText("jLabel5");

        jLabel6.setText("Elemento");

        lbl_elementoArbol.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jc_tipoUusario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_cuenta)
                                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btn_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(112, 112, 112)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(lbl_columna))
                                                .addGap(76, 76, 76)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(lbl_valor)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbl_elementoArbol, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addComponent(lbl_fila)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_tipoNodo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(120, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jc_tipoUusario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_eliminar)))
                    .addComponent(btn_agregar))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_fila)
                    .addComponent(lbl_columna)
                    .addComponent(lbl_valor))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tipoNodo)
                    .addComponent(lbl_elementoArbol))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseClicked
        String nombre =txt_nombre.getText();
        String cuenta = txt_cuenta.getText();
        DefaultTableModel modelo = (DefaultTableModel)jt_tablaUsuarios.getModel();
        Object [] arreglo = {nombre,cuenta};
//        Object [] arreglo2 = new Object[2];
//        arreglo2[0] = nombre;
//        arreglo2[1] = cuenta;
        modelo.addRow(arreglo);
        txt_nombre.setText("");
        txt_cuenta.setText("");        
        // Agregar elemento al arbol.
        
        DefaultTreeModel modeloArbol = (DefaultTreeModel) jt_arbolito.getModel();
        DefaultMutableTreeNode raiz  = (DefaultMutableTreeNode)modeloArbol.getRoot();
        
       
        if(jc_tipoUusario.getSelectedIndex() == 0){ //admin 
            DefaultMutableTreeNode nodoAdministrador = (DefaultMutableTreeNode)raiz.getChildAt(0);
            DefaultMutableTreeNode nuevoNodo = new DefaultMutableTreeNode(nombre);
            nodoAdministrador.add(nuevoNodo);
        }else{ // normal 
               DefaultMutableTreeNode nodoNormal = (DefaultMutableTreeNode)raiz.getChildAt(1);
            DefaultMutableTreeNode nuevoNodo = new DefaultMutableTreeNode(nombre);
            nodoNormal.add(nuevoNodo);
        }
        
        modeloArbol.reload();
        
        
    }//GEN-LAST:event_btn_agregarMouseClicked

    private void jt_tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_tablaUsuariosMouseClicked
            DefaultTableModel modelo = (DefaultTableModel)jt_tablaUsuarios.getModel();
//            int filas = modelo.getRowCount();
//            int columnas = modelo.getColumnCount();
//            System.out.println("Elementos en la tabla");
//            for (int i = 0; i < filas; i++) {
//                for (int j = 0; j < columnas; j++) {
//                    System.out.print(modelo.getValueAt(i, j));
//            }
//                System.out.println("");
//        }

        int columnaseleccionada = jt_tablaUsuarios.getSelectedColumn();
        int filaSeleccionado = jt_tablaUsuarios.getSelectedRow();
        Object valor = modelo.getValueAt(filaSeleccionado, columnaseleccionada);
        
        lbl_fila.setText( filaSeleccionado+ " ");
        lbl_columna.setText(columnaseleccionada+"");
        lbl_valor.setText(valor.toString());
        
        
            
    }//GEN-LAST:event_jt_tablaUsuariosMouseClicked

    private void jt_arbolitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_arbolitoMouseClicked
       DefaultMutableTreeNode nodo =  (DefaultMutableTreeNode)jt_arbolito.getSelectionPath().getLastPathComponent();
      Object elemento =  nodo.getUserObject();
      String valor = elemento.toString();
       System.out.println(nodo);
       lbl_elementoArbol.setText(valor);
       
       Boolean isRoot = nodo.getParent() == null; // RAIZ
       Boolean isNode = nodo.getChildCount() >0; //NODO 
       Boolean isLeaf = nodo.getChildCount() ==0; //HOJA 
       
       if(isRoot){
           lbl_tipoNodo.setText("Raiz");
       }else if(isNode){
           lbl_tipoNodo.setText("Nodo");
       }else{
           lbl_tipoNodo.setText("Hoja");
       }
        
    }//GEN-LAST:event_jt_arbolitoMouseClicked

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
        DefaultMutableTreeNode nodo =  (DefaultMutableTreeNode)jt_arbolito.getSelectionPath().getLastPathComponent();
        DefaultMutableTreeNode padre = (DefaultMutableTreeNode)nodo.getParent();
         DefaultTreeModel modeloArbol = (DefaultTreeModel) jt_arbolito.getModel();
        
        if(nodo.isRoot()){
            JOptionPane.showMessageDialog(null, "No podemos eliminar el padre");
        }else{
            padre.remove(nodo);
             JOptionPane.showMessageDialog(null, "Eliminado");
             modeloArbol.reload();
             
        }
        
       
    }//GEN-LAST:event_btn_eliminarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jc_tipoUusario;
    private javax.swing.JTree jt_arbolito;
    private javax.swing.JTable jt_tablaUsuarios;
    private javax.swing.JLabel lbl_columna;
    private javax.swing.JLabel lbl_elementoArbol;
    private javax.swing.JLabel lbl_fila;
    private javax.swing.JLabel lbl_tipoNodo;
    private javax.swing.JLabel lbl_valor;
    private javax.swing.JTextField txt_cuenta;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
